%% This is the main script of a GUI
% To review that the colloids are being correctly maped into a spin system.
% This is an interactive review of the results obtianed by yesterdays
% script "RefineMappingOfColloidsToSpins".
% It is also very heavily based on the MainWindow of the 
% "DecimationDataProcessing_GUI"

clc
clear
clf

%% First get a list of images
%
% and display the first along with a slider bar, which will be used to
% navigate the image set. 

Directory = 'Dataset/';

F = dir(Directory);
F(arrayfun(@(X)isempty(strfind(X.name,'.bmp')),F))=[];
i = 1;

RemoveArray = [];
AddArray = [];

%% Main Panel
% Figure 1 is the main panel. It contains the result of processing, and the
% controls.

figure(1)
image = uipanel('Position',[0,0.2,1,0.8]);
controls = uipanel('Position',[0,0,1,0.2]);
imax = axes('Parent',image,'Position',[0,0,1,1]);

%% This is the slider that changes between images
ImIndex = uicontrol('Parent',controls,...
    'style','slider',...
    'Units','normalized','Position',[0,0.85,1,0.15],...
    'Min',1,'Max',length(F),'Value',1,...
    'SliderStep',[1,1]/(length(F)-1),...
    'callback','Display');

%% This is the button to remove spurious particles

PrtRemove = uicontrol('Parent',controls,...
    'String','Remove','style','togglebutton',...
    'Units','normalized','Position',[0,0,0.2,0.35],...
    'Callback','Remove');

%% This is a button to add missing particles

PrtAdd = uicontrol('Parent',controls,...
    'String','Add','style','togglebutton',...
    'Units','normalized','Position',[0,0.35,0.2,0.35],...
    'Callback','Add');

%% This is a button to change the scaling and center of the spin system

PrtScale = uicontrol('Parent',controls,...
    'String','ChangeScale','style','togglebutton',...
    'Units','normalized','Position',[0.2,0.35,0.2,0.35],...
    'Callback','ChangeScale');

%% This is a button to flip a single spin given by the cursor

PrtFlip = uicontrol('Parent',controls,...
    'String','ManualSpinFlip','style','pushbutton',...
    'Units','normalized','Position',[0.2,0.0,0.2,0.35],...
    'Callback','ManualSpinFlip');

%% This is a button to change the threshold for particle recognition

ImThresh = uicontrol('Parent',controls,...
    'Tag','Threshold','style','slider',...
    'Units','normalized','Position',[0,0.7,1,0.15],...
    'Min',0,'Max',1,'Value',0.65,...
    'SliderStep',[1,10]/(255),...
    'callback',...
    ['ParamSave.Thresh = get(ImThresh,''Value'');',...
    'save([Name,''.mat''],''ParamSave'');',...
    'Display']);

%% This is a button to change the angle of the figure
Angle = uicontrol('Parent',controls,...
    'style','slider',...
    'Units','normalized','Position',[0.4,0,0.05,0.7],...
    'Min',-pi/20,'Max',pi/20,'Value',0,...
    'callback',...
    ['ParamSave.Rotate = get(Angle,''Value'');',...
    'save([Name,''.mat''],''ParamSave'');',...
    'Display']);


Display

